apiVersion: v1
kind: Service
metadata:
  name: techdemo-service
  namespace: techdemo
spec:
  selector:
    app: techdemo-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
